# Database Configuration
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Activer Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


springdoc.swagger-ui.path=/swagger-ui.html

# Changer l'URL de la documentation OpenAPI JSON
springdoc.api-docs.path=/api-docs

# DÃ©sactiver la banniÃ¨re au dÃ©marrage (optionnel)

spring.main.banner-mode=off
# ? Clé secrète pour signer et vérifier les tokens JWT (change-la pour plus de sécurité)
jwt.secret=yourSuperSecretKey

# ? Durée de validité du token (en millisecondes : ici 1 jour = 86400000 ms)
jwt.expiration=86400000

# ?? Préfixe du token (ex : Authorization: Bearer <token>)
jwt.token.prefix=Bearer

# ? Entête HTTP où le token JWT sera envoyé
jwt.header=Authorization


